---

- name: "[homebrew] Download Homebrew install script"
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: vendor/homebrew/install

- name: "[homebrew] Install Homebrew"
  script: vendor/homebrew/install
  args:
    creates: /usr/local/bin/brew
    executable: ruby

- name: "[homebrew] Update Homebrew"
  homebrew:
    update_homebrew: yes

- name: "[homebrew] Prepare Brewfile"
  template:
    dest: "{{ brewfile_dest }}"
    mode: 0644
    src: "{{ brewfile_src }}"

- name: "[homebrew] Bundle"
  command: brew bundle --file="{{ brewfile_dest }}"

- name: "[homebrew] Clean up old versions"
  command: brew cleanup
