---

#
# Homebrew
#

- name: "[homebrew] Install software"
  include_role:
    name: geerlingguy.homebrew

#
# MAS
#

- name: "[mas] Install software"
  include_role:
    name: geerlingguy.mas
  when: mas_installed_apps
