---

sudo: required
language: objective-c
# 10.14 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode10.2

before_install:
  # Uninstall existing Homebrew installation.
  - curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - chmod +x ./uninstall
  - ./uninstall --force
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

install:
  # Install pip
  - sudo easy_install pip

  # Install Ansible
  - sudo pip install ansible

script:
  # Install dependencies.
  - "ansible-galaxy install -r requirements.yml"

  # Check the playbook's syntax
  - "ansible-playbook main.yml --syntax-check"

  # Copy test config.yml into place
  #- "cp tests/config.yml config.yml"

  # Test the playbook
  - "travis_wait 120 ansible-playbook main.yml -e \"hostname=foobar\""

  # Test the playbook's idempotence
  - idempotence=$(mktemp)
  - "ansible-playbook main.yml -e \"hostname=foobar\" | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
