---

- name: run the playbook tasks on the localhost
  hosts: localhost
  roles:
    - common
    - dev
  vars_prompt:
    - name: "mas_email"
      prompt: "Enter Apple ID"
      private: no
      when: ansible_os_family|lower == 'darwin'
    - name: "mas_password"
      prompt: "Enter password"
      when: ansible_os_family|lower == 'darwin'
