---

#
# Homebrew
#

- name: "[homebrew] Install software"
  include_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_cask_apps:
      - steam
      - teamspeak-client
      - xbox360-controller-driver-unofficial
