---

- name: contains configuration for OS X
  import_tasks: osx.yml
  when: ansible_os_family|lower == 'darwin'

#
# Dotfiles
#

- name: "Clone dotfiles from vcs"
  git:
    repo: git@github.com:christianharke/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"

- name: "Install dotfiles"
  script: "{{ lookup('env', 'HOME') }}/dotfiles/install.sh"
