---

- name: "[dev] Configure OS X"
  import_tasks: osx.yml
  vars:
    homebrew_installed_packages:
      - curl
      - direnv
      - gifsicle
      - git
      - git-lfs
      - go
      - gpg
      - iproute2mac
      - ncdu
      - nmap
      - nvm
      - openssl
      - python@2
      - python3
      - readline
      - shellcheck
      - stow
      - tree
      - vim
      - watch
      - wget
      - wrk
      - yarn
      - zsh
      - zsh-completion
      - zsh-syntax-highlighting
    homebrew_taps:
      - saulpw/vd
    homebrew_cask_apps:
      - docker
      - gpg-suite
      - inssider
      - intellij-idea-ce
      - iterm2
      - java
      - mactex
      - psequel
      - sequel-pro
      - slack
      - teamviewer
      - virtualbox
      - visidata
      - visual-studio-code
      - vmware-fusion
      - wireshark
      # QuickLook plugins
      - qlcolorcode
      - qlstephen
      - qlmarkdown
      - quicklook-json
    mas_installed_apps:
      - { id: 497799835, name: Xcode }
    login_items:
      - { path: "/Applications/iTerm.app", hidden: false }
  when: ansible_os_family|lower == 'darwin'

#
# Dotfiles
#

- name: "[dev] Clone dotfiles from vcs"
  git:
    repo: https://github.com/christianharke/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"

- name: "[dev] Install dotfiles"
  script: "{{ lookup('env', 'HOME') }}/dotfiles/install.sh --all"
