---

- name: "[dev] Configure OS X"
  import_tasks: osx.yml
  when: ansible_os_family|lower == 'darwin'

#
# Dotfiles
#

- name: "[dev] Clone dotfiles from vcs"
  git:
    repo: https://github.com/christianharke/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"

- name: "[dev] Install dotfiles"
  script: "{{ lookup('env', 'HOME') }}/dotfiles/install.sh --all"
