---

#
# Homebrew
#

- name: "[homebrew] Install software"
  include_role:
    name: geerlingguy.homebrew

#
# MAS
#

- name: "[mas] Install software"
  include_role:
    name: geerlingguy.mas
  when: mas_installed_apps

#
# ZSH
#

- name: "[zsh] Download oh-my-zsh install script"
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: vendor/oh-my-zsh/install.sh

- name: "[zsh] Install oh-my-zsh"
  script: vendor/oh-my-zsh/install.sh
  args:
    creates: ~/.oh-my-zsh/oh-my-zsh.sh

#
# System
#

- name: "[system] Run osx-add-login-items"
  include_role:
    name: osx-add-login-items

#
# iOS
#

- name: "[ios] Add iOS Simulator to Applications folder"
  file:
    path: /Applications/Simulator.app
    src: /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
    state: link
  become: true
