---

- name: "Include os-specific variables"
  include_vars: osx.yml

#
# Homebrew
#

- name: "[homebrew] Download Homebrew install script"
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: vendor/homebrew/install

- name: "[homebrew] Install Homebrew"
  script: vendor/homebrew/install
  args:
    creates: /usr/local/bin/brew
    executable: ruby

- name: "[homebrew] Update Homebrew"
  homebrew:
    update_homebrew: yes

- name: "[homebrew] Prepare Brewfile"
  template:
    dest: "{{ brewfile_dest }}"
    mode: 0644
    src: "{{ brewfile_src }}"

- name: "[homebrew] Bundle"
  command: brew bundle --file="{{ brewfile_dest }}"

- name: "[homebrew] Clean up old versions"
  command: brew cleanup

#
# ZSH
#

- name: "[zsh] Download oh-my-zsh install script"
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: vendor/oh-my-zsh/install.sh

- name: "[zsh] Install oh-my-zsh"
  script: vendor/oh-my-zsh/install.sh
  args:
    creates: ~/.oh-my-zsh/oh-my-zsh.sh

- name: "[zsh] Copy .zshrc"
  template:
    dest: ~/.zshrc
    src: osx/.zshrc

#
# iOS
#

#- name: "[ios] Add iOS Simulator to Applications folder"
#  file:
#    path: /Applications/Simulator.app
#    src: /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
#    state: link
#  become: true
