---

- name: "Include os-specific variables"
  include_vars: osx.yml

#
# Homebrew
#

- name: Run homebrew-bundle
  include_role:
    name: homebrew-bundle

#
# ZSH
#

- name: "[zsh] Download oh-my-zsh install script"
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: vendor/oh-my-zsh/install.sh

- name: "[zsh] Install oh-my-zsh"
  script: vendor/oh-my-zsh/install.sh
  args:
    creates: ~/.oh-my-zsh/oh-my-zsh.sh

- name: "[zsh] Copy .zshrc"
  template:
    dest: ~/.zshrc
    src: osx/.zshrc

#
# System
#

- name: "[system] Set login items"
  command: osascript -e 'tell application "System Events" to make login item at end with properties {path:"{{ item.path }}", hidden:{{ item.hidden }}}'
  loop:
    - { path: "/Applications/iTerm.app", hidden: false }

#
# iOS
#

#- name: "[ios] Add iOS Simulator to Applications folder"
#  file:
#    path: /Applications/Simulator.app
#    src: /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
#    state: link
#  become: true
