---

#
# Homebrew
#

- name: "[homebrew] Install software"
  include_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_installed_packages:
      - curl
      - direnv
      - gifsicle
      - git
      - git-lfs
      - go
      - gpg
      - iproute2mac
      - nmap
      - nvm
      - openssl
      - python@2
      - python3
      - readline
      - shellcheck
      - stow
      - tldr
      - tree
      - watch
      - wget
      - wrk
      - yarn
      - zsh
      - zsh-completion
      - zsh-syntax-highlighting
    homebrew_taps:
      - saulpw/vd
    homebrew_cask_apps:
      - docker
      - gpg-suite
      - inssider
      - intellij-idea-ce
      - iterm2
      - java
      - mactex
      - macvim
      - psequel
      - sequel-pro
      - slack
      - teamviewer
      - virtualbox
      - visidata
      - visual-studio-code
      - vmware-fusion
      - wireshark
      # QuickLook plugins
      - qlcolorcode
      - qlstephen
      - qlmarkdown
      - quicklook-json

#
# MAS
#

- name: "[mas] Install software"
  include_role:
    name: geerlingguy.mas
  vars:
    mas_installed_apps:
      - { id: 497799835, name: Xcode }

#
# ZSH
#

- name: "[zsh] Download oh-my-zsh install script"
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: vendor/oh-my-zsh/install.sh

- name: "[zsh] Install oh-my-zsh"
  script: vendor/oh-my-zsh/install.sh
  args:
    creates: ~/.oh-my-zsh/oh-my-zsh.sh

#
# System
#

- name: "Run osx-add-login-items"
  include_role:
    name: osx-add-login-items
  vars:
    login_items:
      - { path: "/Applications/iTerm.app", hidden: false }

#
# iOS
#

#- name: "[ios] Add iOS Simulator to Applications folder"
#  file:
#    path: /Applications/Simulator.app
#    src: /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
#    state: link
#  become: true
