---

#
# Homebrew
#

homebrew_cask_apps:
  - 1password
  - adobe-acrobat-reader
  - boostnote
  - caffeine
  - dockutil
  - firefox
  - forklift
  - google-chrome
  - keepassxc
  - keka
  - libreoffice
  - licecap
  - microsoft-office
  - spectacle
  - tunnelblick
  - vlc
  # QuickLook plugins
  - suspicious-package

#
# MAS
#

mas_installed_apps:
  - { id: 410628904, name: Wunderlist }

#
# Dock
#

dockitems_to_remove:
  - Siri
  - Launchpad
  - Safari
  - Mail
  - Notizen       # Notes
  - Erinnerungen  # Reminders
  - Nachrichten   # Messages
  - FaceTime
  - iTunes
  - Bücher        # Books
dockitems_to_persist:
  # Contacts
  - name: Kontakte
    pos: 1
  # Calendar
  - name: Kalender
    pos: 2
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 3
  # Maps
  - name: Karten
    pos: 4
  # Photos
  - name: Fotos
    pos: 5
  - name: App Store
    pos: 6
  # System Preferences
  - name: Systemeinstellungen
    pos: 7
